### ISSUE TITLE
Mednafen version is not compatible

### ISSUE THREAD

**Issue by qvolant** [AmatCoder/mednaffe#33]
I'm using Mednafen 0.9.38.7 (installed from Debian stretch repos) but when starting Mednaffe I get an error message :

`Error: Mednafen version is not compatible.
You need 0.9.36.2 version or above.`

I may be wrong but it seems to me that 0.9.38.7 is above 0.9.36.2 ?

**Comment by qvolant** [comment]
Nevermind.

Found the solution in [another issue](https://github.com/AmatCoder/mednaffe/issues/24#issuecomment-239649821)

**Comment by cpcbegin** [comment]
I use Debian 9 stable 64 bits and I have the same error.
I shows:
Error: Mednafen version is not compatible.
You need 0.9.41 version or above.
But Mednafen 0.9.41 is installed.

**Comment by AmatCoder** [comment]
@cpcbegin 

Debian 9 contains an old version of mednaffe (0.8.4) in repositories.
This version had a bug (issue #52 ) when certain localizations (i.e. spanish) are used.
It was fixed in 0.8.5 version.

A workaround is to run "**LANG=C mednaffe**" in a terminal.

You can read the Debian bug report [here](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=890482).
