### ISSUE TITLE
The comma seperated list is too literal.

### ISSUE THREAD

**Issue by doyousketch2** [AmatCoder/mednaffe#45]
You need to allow *. and space characters, because everybody that has ever typed in file extensions type in *.zip, *.cue, *.pce    so-on-and-so-forth.

Even though you typed in the format you prefer, I guarantee everybody is going to try the way they are familiar with first, then discover none of the files they specified are showing up in their directories.

**Comment by AmatCoder** [comment]
I think that the problem is that label is wrong: 'Comma-separated list of filetypes to show' 

It should be: 'Comma-separated list of **extensions** to show' since mednaffe just looks for extensions 
not filenames. So things like wildcards are not suitable, I believe.

But I am agree that space characters should be trimmed.

**Comment by AmatCoder** [comment]
Fixed on 5dfdb5d commit.
