### ISSUE TITLE
Suggestions - quality of life features, snes_faust and rom directories.

### ISSUE THREAD

**Issue by davidrahd** [AmatCoder/mednaffe#96]
Just a couple quality of life suggestions:

For some of us using mednafen in low-end machines, it would be nice to have the option to select a core for systems that have multiple ones like snes/snes_faust and pce/pce_fast or for them to appear as separated systems with the option to enable <on/off>.
I can disable the snes core and enable snes_faust core in the mednafen config file and it will work when launching games from mednaffe but every change I make in the config using mednaffe options only change those configs for the default snes core, so I have to manually change in the mednafen config file all the snes_faust options I want.

The room directories in the the drop down menu appear in the order they were chosen, it easy to just edit the mednaffe config file and edit the locations and ordering but an option to change the order after they are chosen or even an pop-up window to edit the directories would be appreciate.  

I used to just run mednafen in the command line or to make an option to "open with mednafen" for zip and cue files in my file manager, but mednaffe is a very good and slim launcher. Thank you.

**Comment by AmatCoder** [comment]
- _snes_faust/pce_fast_ will be developmented but as separated systems (mainly because they do not share all the options with regular _snes/pce_ systems).

- Ordering the rom directories is already implemented:

![Untitled](https://user-images.githubusercontent.com/3890995/57275081-a14f0e80-709d-11e9-84ce-6023801c2d92.png)

You can use up/down buttons for that. Editing the directories is not possible for the time being.

Thanks for suggestions.

**Comment by davidrahd** [comment]
Thanks, didn't find the option to manage folders, probably cos I'm not using the last git code.
Wow! Is that support for game screenshots/artwork in the image? Very nice! I will try to pull the last git code later.
